// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/processdata.proto

package go_micro_srv_processdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for StoreData service

func NewStoreDataEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for StoreData service

type StoreDataService interface {
	Store(ctx context.Context, in *StoreRequest, opts ...client.CallOption) (*StoreRespons, error)
}

type storeDataService struct {
	c    client.Client
	name string
}

func NewStoreDataService(name string, c client.Client) StoreDataService {
	return &storeDataService{
		c:    c,
		name: name,
	}
}

func (c *storeDataService) Store(ctx context.Context, in *StoreRequest, opts ...client.CallOption) (*StoreRespons, error) {
	req := c.c.NewRequest(c.name, "StoreData.Store", in)
	out := new(StoreRespons)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StoreData service

type StoreDataHandler interface {
	Store(context.Context, *StoreRequest, *StoreRespons) error
}

func RegisterStoreDataHandler(s server.Server, hdlr StoreDataHandler, opts ...server.HandlerOption) error {
	type storeData interface {
		Store(ctx context.Context, in *StoreRequest, out *StoreRespons) error
	}
	type StoreData struct {
		storeData
	}
	h := &storeDataHandler{hdlr}
	return s.Handle(s.NewHandler(&StoreData{h}, opts...))
}

type storeDataHandler struct {
	StoreDataHandler
}

func (h *storeDataHandler) Store(ctx context.Context, in *StoreRequest, out *StoreRespons) error {
	return h.StoreDataHandler.Store(ctx, in, out)
}
