// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/processdata.proto

package go_micro_srv_processdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreRequest struct {
	DataBase             string     `protobuf:"bytes,1,opt,name=dataBase,proto3" json:"dataBase,omitempty"`
	Details              []*any.Any `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7842953a67f0b108, []int{0}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetDataBase() string {
	if m != nil {
		return m.DataBase
	}
	return ""
}

func (m *StoreRequest) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type StoreRespons struct {
	DataId               int64    `protobuf:"varint,1,opt,name=dataId,proto3" json:"dataId,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRespons) Reset()         { *m = StoreRespons{} }
func (m *StoreRespons) String() string { return proto.CompactTextString(m) }
func (*StoreRespons) ProtoMessage()    {}
func (*StoreRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_7842953a67f0b108, []int{1}
}

func (m *StoreRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRespons.Unmarshal(m, b)
}
func (m *StoreRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRespons.Marshal(b, m, deterministic)
}
func (m *StoreRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRespons.Merge(m, src)
}
func (m *StoreRespons) XXX_Size() int {
	return xxx_messageInfo_StoreRespons.Size(m)
}
func (m *StoreRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRespons.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRespons proto.InternalMessageInfo

func (m *StoreRespons) GetDataId() int64 {
	if m != nil {
		return m.DataId
	}
	return 0
}

func (m *StoreRespons) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*StoreRequest)(nil), "go.micro.srv.processdata.StoreRequest")
	proto.RegisterType((*StoreRespons)(nil), "go.micro.srv.processdata.StoreRespons")
}

func init() { proto.RegisterFile("proto/processdata.proto", fileDescriptor_7842953a67f0b108) }

var fileDescriptor_7842953a67f0b108 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0x31, 0x4f, 0x02, 0x41,
	0x10, 0x85, 0x05, 0x22, 0xc8, 0x68, 0xb5, 0x31, 0xba, 0x5e, 0x45, 0xae, 0x30, 0x54, 0x73, 0x09,
	0xfe, 0x01, 0x35, 0x36, 0xb6, 0x6b, 0xa5, 0xdd, 0xc0, 0x0d, 0x1b, 0x12, 0xb8, 0x39, 0x77, 0x16,
	0x13, 0xfe, 0xbd, 0x61, 0xf0, 0x08, 0x8d, 0xa1, 0xfc, 0x76, 0xdf, 0xfb, 0x76, 0x1f, 0xdc, 0xb7,
	0x49, 0xb2, 0x54, 0x6d, 0x92, 0x05, 0xab, 0xd6, 0x94, 0x09, 0xed, 0xc4, 0xf9, 0x28, 0xb8, 0x59,
	0x2d, 0x92, 0xa0, 0xa6, 0x1f, 0x3c, 0xb9, 0x2f, 0x1e, 0xa2, 0x48, 0x5c, 0x73, 0x65, 0xb9, 0xf9,
	0x76, 0x59, 0x51, 0xb3, 0x3b, 0x94, 0xca, 0x2f, 0xb8, 0xf9, 0xc8, 0x92, 0x38, 0xf0, 0xf7, 0x96,
	0x35, 0xbb, 0x02, 0xae, 0xf6, 0x95, 0x57, 0x52, 0xf6, 0xbd, 0x49, 0x6f, 0x3a, 0x0e, 0x47, 0x76,
	0x08, 0xa3, 0x9a, 0x33, 0xad, 0xd6, 0xea, 0xfb, 0x93, 0xc1, 0xf4, 0x7a, 0x76, 0x8b, 0x07, 0x31,
	0x76, 0x62, 0x7c, 0x69, 0x76, 0xa1, 0x0b, 0x95, 0xcf, 0x47, 0xb7, 0xb6, 0xd2, 0xa8, 0xbb, 0x83,
	0xe1, 0xde, 0xf5, 0x5e, 0x9b, 0x79, 0x10, 0xfe, 0xc8, 0x79, 0x18, 0x6d, 0x58, 0x95, 0x22, 0xfb,
	0xbe, 0x3d, 0xd9, 0xe1, 0x6c, 0x09, 0x63, 0x33, 0xbc, 0x51, 0x26, 0xf7, 0x09, 0x97, 0x06, 0xee,
	0x11, 0xff, 0x5b, 0x8a, 0xa7, 0x5b, 0x8a, 0xf3, 0x39, 0xfb, 0x57, 0x79, 0x31, 0x1f, 0xda, 0x80,
	0xa7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xec, 0xff, 0x35, 0xa4, 0x5c, 0x01, 0x00, 0x00,
}
