// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mweb.proto

package go_micro_srv_sendmweb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TryRequest) Reset()         { *m = TryRequest{} }
func (m *TryRequest) String() string { return proto.CompactTextString(m) }
func (*TryRequest) ProtoMessage()    {}
func (*TryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cd02bd838a20ad2, []int{0}
}

func (m *TryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TryRequest.Unmarshal(m, b)
}
func (m *TryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TryRequest.Marshal(b, m, deterministic)
}
func (m *TryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TryRequest.Merge(m, src)
}
func (m *TryRequest) XXX_Size() int {
	return xxx_messageInfo_TryRequest.Size(m)
}
func (m *TryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TryRequest proto.InternalMessageInfo

func (m *TryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TryRespons struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TryRespons) Reset()         { *m = TryRespons{} }
func (m *TryRespons) String() string { return proto.CompactTextString(m) }
func (*TryRespons) ProtoMessage()    {}
func (*TryRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cd02bd838a20ad2, []int{1}
}

func (m *TryRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TryRespons.Unmarshal(m, b)
}
func (m *TryRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TryRespons.Marshal(b, m, deterministic)
}
func (m *TryRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TryRespons.Merge(m, src)
}
func (m *TryRespons) XXX_Size() int {
	return xxx_messageInfo_TryRespons.Size(m)
}
func (m *TryRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_TryRespons.DiscardUnknown(m)
}

var xxx_messageInfo_TryRespons proto.InternalMessageInfo

func (m *TryRespons) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*TryRequest)(nil), "go.micro.srv.sendmweb.TryRequest")
	proto.RegisterType((*TryRespons)(nil), "go.micro.srv.sendmweb.TryRespons")
}

func init() { proto.RegisterFile("proto/mweb.proto", fileDescriptor_0cd02bd838a20ad2) }

var fileDescriptor_0cd02bd838a20ad2 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4f, 0x4d, 0xd2, 0x03, 0x33, 0x85, 0x44, 0xd3, 0xf3, 0xf5, 0x72, 0x33,
	0x93, 0x8b, 0xf2, 0xf5, 0x8a, 0x8b, 0xca, 0xf4, 0x8a, 0x53, 0xf3, 0x52, 0x40, 0x92, 0x4a, 0x0a,
	0x5c, 0x5c, 0x21, 0x45, 0x95, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c,
	0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x1c, 0x54,
	0x45, 0x71, 0x41, 0x7e, 0x5e, 0xb1, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0x54, 0x01, 0x88,
	0x69, 0x14, 0xc5, 0xc5, 0xe2, 0x5b, 0x9e, 0x9a, 0x24, 0x14, 0xc4, 0xc5, 0x11, 0x9c, 0x9a, 0x97,
	0x02, 0x66, 0x2b, 0xea, 0x61, 0xb5, 0x4d, 0x0f, 0x61, 0x95, 0x14, 0x5e, 0x25, 0x60, 0xbb, 0x94,
	0x18, 0x92, 0xd8, 0xc0, 0x6e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x52, 0xd9, 0x95, 0x84,
	0xcf, 0x00, 0x00, 0x00,
}
