// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/showdataweb.proto

package go_micro_srv_ShowData

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TryRequest struct {
	Flag                 int64    `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TryRequest) Reset()         { *m = TryRequest{} }
func (m *TryRequest) String() string { return proto.CompactTextString(m) }
func (*TryRequest) ProtoMessage()    {}
func (*TryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35875ba34c67532, []int{0}
}

func (m *TryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TryRequest.Unmarshal(m, b)
}
func (m *TryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TryRequest.Marshal(b, m, deterministic)
}
func (m *TryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TryRequest.Merge(m, src)
}
func (m *TryRequest) XXX_Size() int {
	return xxx_messageInfo_TryRequest.Size(m)
}
func (m *TryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TryRequest proto.InternalMessageInfo

func (m *TryRequest) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type TryRespons struct {
	Crontabres           bool     `protobuf:"varint,1,opt,name=crontabres,proto3" json:"crontabres,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TryRespons) Reset()         { *m = TryRespons{} }
func (m *TryRespons) String() string { return proto.CompactTextString(m) }
func (*TryRespons) ProtoMessage()    {}
func (*TryRespons) Descriptor() ([]byte, []int) {
	return fileDescriptor_f35875ba34c67532, []int{1}
}

func (m *TryRespons) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TryRespons.Unmarshal(m, b)
}
func (m *TryRespons) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TryRespons.Marshal(b, m, deterministic)
}
func (m *TryRespons) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TryRespons.Merge(m, src)
}
func (m *TryRespons) XXX_Size() int {
	return xxx_messageInfo_TryRespons.Size(m)
}
func (m *TryRespons) XXX_DiscardUnknown() {
	xxx_messageInfo_TryRespons.DiscardUnknown(m)
}

var xxx_messageInfo_TryRespons proto.InternalMessageInfo

func (m *TryRespons) GetCrontabres() bool {
	if m != nil {
		return m.Crontabres
	}
	return false
}

func (m *TryRespons) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*TryRequest)(nil), "go.micro.srv.ShowData.TryRequest")
	proto.RegisterType((*TryRespons)(nil), "go.micro.srv.ShowData.TryRespons")
}

func init() { proto.RegisterFile("proto/showdataweb.proto", fileDescriptor_f35875ba34c67532) }

var fileDescriptor_f35875ba34c67532 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0xc8, 0x2f, 0x4f, 0x49, 0x2c, 0x49, 0x2c, 0x4f, 0x4d, 0xd2, 0x03, 0x8b,
	0x08, 0x89, 0xa6, 0xe7, 0xeb, 0xe5, 0x66, 0x26, 0x17, 0xe5, 0xeb, 0x15, 0x17, 0x95, 0xe9, 0x05,
	0x67, 0xe4, 0x97, 0xbb, 0x24, 0x96, 0x24, 0x2a, 0x29, 0x70, 0x71, 0x85, 0x14, 0x55, 0x06, 0xa5,
	0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0xa4, 0xe5, 0x24, 0xa6, 0x4b, 0x30, 0x2a,
	0x30, 0x6a, 0x30, 0x07, 0x81, 0xd9, 0x4a, 0x76, 0x50, 0x15, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0x42,
	0x72, 0x5c, 0x5c, 0xc9, 0x45, 0xf9, 0x79, 0x25, 0x89, 0x49, 0x45, 0xa9, 0xc5, 0x60, 0x75, 0x1c,
	0x41, 0x48, 0x22, 0x42, 0x02, 0x5c, 0xcc, 0xb9, 0xc5, 0xe9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x20, 0xa6, 0x51, 0x0a, 0x17, 0x07, 0xcc, 0x36, 0xa1, 0x08, 0x2e, 0x3e, 0xf7, 0xd4, 0x12,
	0x10, 0xd3, 0x19, 0xa2, 0x45, 0x48, 0x51, 0x0f, 0xab, 0xbb, 0xf4, 0x10, 0x8e, 0x92, 0xc2, 0xab,
	0x04, 0xec, 0x2a, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x2f, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x94, 0x29, 0x4b, 0x0c, 0x00, 0x01, 0x00, 0x00,
}
