// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/showdataweb.proto

package go_micro_srv_showdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShowData service

func NewShowDataEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShowData service

type ShowDataService interface {
	GetDataCrontab(ctx context.Context, in *TryRequest, opts ...client.CallOption) (*TryRespons, error)
}

type showDataService struct {
	c    client.Client
	name string
}

func NewShowDataService(name string, c client.Client) ShowDataService {
	return &showDataService{
		c:    c,
		name: name,
	}
}

func (c *showDataService) GetDataCrontab(ctx context.Context, in *TryRequest, opts ...client.CallOption) (*TryRespons, error) {
	req := c.c.NewRequest(c.name, "ShowData.GetDataCrontab", in)
	out := new(TryRespons)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShowData service

type ShowDataHandler interface {
	GetDataCrontab(context.Context, *TryRequest, *TryRespons) error
}

func RegisterShowDataHandler(s server.Server, hdlr ShowDataHandler, opts ...server.HandlerOption) error {
	type showData interface {
		GetDataCrontab(ctx context.Context, in *TryRequest, out *TryRespons) error
	}
	type ShowData struct {
		showData
	}
	h := &showDataHandler{hdlr}
	return s.Handle(s.NewHandler(&ShowData{h}, opts...))
}

type showDataHandler struct {
	ShowDataHandler
}

func (h *showDataHandler) GetDataCrontab(ctx context.Context, in *TryRequest, out *TryRespons) error {
	return h.ShowDataHandler.GetDataCrontab(ctx, in, out)
}
