// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/requestapi.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SendAPI service

type SendAPIService interface {
	ProcessAPI(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*GetRespons, error)
}

type sendAPIService struct {
	c    client.Client
	name string
}

func NewSendAPIService(name string, c client.Client) SendAPIService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.requestapi"
	}
	return &sendAPIService{
		c:    c,
		name: name,
	}
}

func (c *sendAPIService) ProcessAPI(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*GetRespons, error) {
	req := c.c.NewRequest(c.name, "SendAPI.ProcessAPI", in)
	out := new(GetRespons)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SendAPI service

type SendAPIHandler interface {
	ProcessAPI(context.Context, *SendRequest, *GetRespons) error
}

func RegisterSendAPIHandler(s server.Server, hdlr SendAPIHandler, opts ...server.HandlerOption) error {
	type sendAPI interface {
		ProcessAPI(ctx context.Context, in *SendRequest, out *GetRespons) error
	}
	type SendAPI struct {
		sendAPI
	}
	h := &sendAPIHandler{hdlr}
	return s.Handle(s.NewHandler(&SendAPI{h}, opts...))
}

type sendAPIHandler struct {
	SendAPIHandler
}

func (h *sendAPIHandler) ProcessAPI(ctx context.Context, in *SendRequest, out *GetRespons) error {
	return h.SendAPIHandler.ProcessAPI(ctx, in, out)
}
